# Generated by Django 5.2.3 on 2025-06-11 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20, verbose_name='status')),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum budget')),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum budget')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='deadline date')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('selected_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to=settings.AUTH_USER_MODEL, verbose_name='selected freelancer')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='bid amount')),
                ('proposal_text', models.TextField(verbose_name='proposal text')),
                ('bid_date', models.DateTimeField(auto_now_add=True, verbose_name='bid date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_made', to=settings.AUTH_USER_MODEL, verbose_name='freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'bid',
                'verbose_name_plural': 'bids',
                'ordering': ['-bid_date'],
                'unique_together': {('project', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='rating')),
                ('comment', models.TextField(verbose_name='comment')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='review date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.project', verbose_name='project')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='reviewee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-review_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='reviewer_cannot_be_reviewee')],
                'unique_together': {('project', 'reviewer', 'reviewee')},
            },
        ),
    ]
